service: habit-tracker-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-north-1
  profile: habit-tracker

  iam:
    role: arn:aws:iam::635104184831:role/habit-tracker-backend-dev-eu-north-1-lambdaRole

  environment:
    USERS_TABLE: ${self:custom.usersTable}
    HABITS_TABLE: ${self:custom.habitsTable}
    COMPLETIONS_TABLE: ${self:custom.completionsTable}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}

custom:
  usersTable: habit-tracker-users
  habitsTable: habit-tracker-habits
  completionsTable: habit-tracker-completions
  cognitoArn: arn:aws:cognito-idp:eu-north-1:635104184831:userpool/eu-north-1_tHSuinBiR

functions:
  # --- AUTH ---
  createUser:
    handler: functions/auth/createUser/handler.createUser
    events:
      - http:
          path: /auth/users
          method: post
          cors: true

  login:
    handler: functions/auth/login/handler.login
    events:
      - http:
          path: /auth/login
          method: post
          cors: true

  # --- HABITS ---
  createHabit:
    handler: functions/habits/handler.createHabit
    events:
      - http:
          path: /habits
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoArn}

  getHabits:
    handler: functions/habits/handler.getHabits
    events:
      - http:
          path: /habits
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoArn}

  updateHabit:
    handler: functions/habits/handler.updateHabit
    events:
      - http:
          path: /habits/{habitId}
          method: patch
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoArn}

  deleteHabit:
    handler: functions/habits/handler.deleteHabit
    events:
      - http:
          path: /habits/{habitId}
          method: delete
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoArn}

  # --- TRACKING ---
  completeHabit:
    handler: functions/tracking/handler.completeHabit
    events:
      - http:
          path: /completions
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoArn}

  getCompletions:
    handler: functions/tracking/handler.getCompletions
    events:
      - http:
          path: /completions
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoArn}

  deleteCompletion:
    handler: functions/tracking/handler.deleteCompletion
    events:
      - http:
          path: /completions/{completionId}
          method: delete
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoArn}

plugins: []

package:
  exclude:
    - node_modules/**
    - .git/**
    - .env
    - README.md
    - tests/**
    - .vscode/**
    - serverless.yml
    - package-lock.json
    - .DS_Store
  include:
    - functions/**
    - lib/**
